### ISSUE TITLE
Two different versions of @optimizely/js-sdk-utils in final bundle

### ISSUE THREAD

**Issue by angel-rs** [optimizely/react-sdk#103]
Hello!

I'm currently working improving load times of a web-app & noticed thanks to [inspectpack](https://github.com/FormidableLabs/inspectpack) that on the app final bundle there are two different versions of `@optimizely/js-sdk-utils`, `0.1.0` & `0.4.0`

see the report here:

![image](https://user-images.githubusercontent.com/20560880/108428272-ae0e0980-7214-11eb-894f-e005ef0f9dd5.png)

I could resolve it setting a `resolution` to always use `0.4.0`, but not sure if safe? could lead to bad functioning of the library? Also would like for this library to not introduce duplicates (& increase bundlesize/loadtimes) since I like it & use it on various projects :)

What's a feasible solution? is there any reason in particular `@optimizely/react-sdk` is still using `@optimizely/js-sdk-utils@0.1.0` ?

**Comment by zashraf1985** [comment]
We just fixed this in [`@optimizely/react-sdk 2.8.0`](https://github.com/optimizely/react-sdk/releases/tag/2.8.0)
