### ISSUE TITLE
React-Redux "connect" not working with "withOptimizely"

### ISSUE THREAD

**Issue by wchavarria03** [optimizely/react-sdk#110]
I am trying to connect Optimizely with a component connected with react-redux.

I have the following code

```
export class Report extends Component {
  constructor(props) {
    super(props);
    ....   
}

export default connect(mapStateToProps, { abTestCreate, reportResetErrors })(Report);
```

I need to connect that component using "withOptimizely", I tried the following 2 approaches and they didn't work, not sure if there is something I can do 
```
const ConnectedReport = connect(mapStateToProps, { abTestCreate, reportResetErrors })(Report);
export default withOptimizely(ConnectedReport);
```

```
const OptimizelyReport = withOptimizely(Report);
export default connect(mapStateToProps, { abTestCreate, reportResetErrors })(OptimizelyReport);
```

Any suggestion about how to make them work together please ?

**Comment by michaellin986** [comment]
@wchavarria03 I encountered the same issue; how did you resolve it?
