### ISSUE TITLE
Replace @react-native-community/async-storage with @react-native-async-storage/async-storage

### ISSUE THREAD

**Issue by wildseansy** [optimizely/react-sdk#111]
In the [docs is says](https://docs.developers.optimizely.com/full-stack/docs/install-sdk-reactnative)

```bash
yarn add @react-native-community/async-storage
yarn add @react-native-community/netinfo
```

However `@react-native-community/async-storage` is a [deprecated project](https://www.npmjs.com/package/@react-native-community/async-storage), and has been replaced by  [@react-native-async-storage/async-storage](https://react-native-async-storage.github.io/async-storage/docs/install/) (with the same API, for now).  Please update to use the modern tool. Using optimizely's react sdk in React Native projects will not allow using the new tool, as it expects `@react-native-community/async-storage` to be present.

Perhaps the best way to build storage in is dependency injection. `Storybook` is initialized this way, allowing to [specify your instance of async storage](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-native-async-storage)

```typescript
import AsyncStorage form "@react-native-async-storage/async-storage";
// or import AsyncStorage from "@react-native-community/async-storage";

getStorybookUI({
  ...
  asyncStorage: AsyncStorage
});
```

**Comment by professorkolik** [comment]
Any timeframe when it can be upgraded, I saw for other packages within `@optimizely` already upgraded?

**Comment by michaelonesimplicity** [comment]
Hello, can this be please fixed? Our company really wants to use Optimizely with Expo but we can't because of this issue.

**Comment by michaelonesimplicity** [comment]
Any updates on this?

**Comment by Estebank94** [comment]
I need this too

**Comment by michaelonesimplicity** [comment]
Guys are you working on this please?

**Comment by Estebank94** [comment]
No news?

**Comment by yavorona** [comment]
@wildseansy @professorkolik @michaelonesimplicity @Estebank94 @gursesl the deprecated `@react-native-community/async-storage` packaged has been replaced with `@react-native-async-storage/async-storage` directly in `optimizely/optimizely-sdk` [v4.6.0](https://www.npmjs.com/package/@optimizely/optimizely-sdk/v/4.6.0). Please upgrade to the latest `@optimizely/react-sdk` [v4.6.1](https://www.npmjs.com/package/@optimizely/react-sdk/v/2.6.1) which contains the  most recent version of `optimizely/optimizely-sdk` package. The documentation will be updated in the next couple of days. Thanks!
