### ISSUE TITLE
Unmet peer dependency issues with @react-native-community packages

### ISSUE THREAD

**Issue by mhatvan** [optimizely/react-sdk#115]
As a React (not React Native) user, I would expect the following packages to be declared as optional peer dependencies to avoid unmet peer dependency issues:

- `@react-native-community/async-storage`
- `@react-native-community/netinfo`

**Comment by zashraf1985** [comment]
@mhatvan As per our understanding, making a dependency `optional` would mean, it will always install if available but wont throw any errors/warning if not available for some reason. This eventually means it will always install these for all the users if we make it optional. On the contrary, keeping these as peer dependencies only throw a warning but don't install these for the non react native users which is what we intended. We understand that the ideal solution would be to not throw a warning for non react native use cases but unfortunately we don't see simple solution for that yet.

**Comment by mikecousins** [comment]
It's even bigger than that and IMO this should not be closed. It makes it impossible to use any "strict" package manager (pnpm, yarn v2/3, etc) without installing extraneous packages.

**Comment by zashraf1985** [comment]
@mhatvan I tried `optionalDependencies` but that did not work as intended. I just stumbled upon `peerDependenciesMeta`. I will give it a try and see if it works.. reopening this for now.

**Comment by zashraf1985** [comment]
@mikecousins @mhatvan I just made those peer dependencies optional. Please check and let us know if this resolves the issue.

**Comment by mhatvan** [comment]
I am not working on that client project anymore, unfortunately. But thanks for the initiative!
