### ISSUE TITLE
type VariableValuesObject doesn't handle JSON

### ISSUE THREAD

**Issue by timothympace** [optimizely/react-sdk#117]
When a variable is defined as JSON in the optimizely web interface, there is no associated typing for it on [`VariableValuesObject`](https://github.com/optimizely/react-sdk/blob/57b68da7688a209f51736c1030b13d620a52ac11/src/client.ts#L23). However, the SDK handles `JSON.parse`-ing variables of this type via [`getFeatureVariableJSON`](https://github.com/optimizely/react-sdk/blob/57b68da7688a209f51736c1030b13d620a52ac11/src/client.ts#L597). This leads to a type mismtach when using `useFeature` or `<OptimizelyFeature />`.

I might just be missing a key detail here, let me know if I'm using the SDK in an invalid way.

**Comment by yavorona** [comment]
@timothympace thanks for reporting the issue! We just released a new patch [v2.6.3](https://www.npmjs.com/package/@optimizely/react-sdk/v/2.6.3) with the fix.

**Comment by timothympace** [comment]
@yavorona Thank you for the quick fix!
