### ISSUE TITLE
What is the difference between useFeature and useDecision hooks?

### ISSUE THREAD

**Issue by khanilov** [optimizely/react-sdk#122]
Hello 👋 

I see that since 2.5 version you introduced `useDecision` hook and updated all docs to use it, but I am not able to find any motivation behind that. Also now there are no docs about `useFeature` hook, that leads to confusion over should we continue use it or not.

Can you please explain the differences of `useFeature` and `useDecision` hooks and what are the future support plans for `useFeature` hook since `useDecision` was introduced?

Thanks

**Comment by yavorona** [comment]
Hi @khanilov,

Thanks for providing your feedback!

We introduced new `useDecision` as a part of a new interface for retrieving feature flag status and associated experiment decisions for users. Please check out this [page](https://docs.developers.optimizely.com/full-stack/v4.0/docs/migrate-from-older-versions-react) where we provide code samples for using new `useDecision`  in lieu of existing `useFeature` and `useExperiment` hooks.  As you can see, these are more flexible and easier to use replacements! 

We recommend adopting new `useDecision` hook as we are planning to deprecate old `useFeature` and `useExperiment` hooks along with the `OptimizelyExperiment` and `OptimizelyVariation` components in the next major version. We are currently working on updating the documentation to make it more clear. 

More information on `useFeature` and `useExperiment` hooks can be found in legacy docs here:
https://docs.developers.optimizely.com/full-stack/docs/hooks-react

**Comment by khanilov** [comment]
@yavorona Thanks!
