### ISSUE TITLE
30KB Gzipped 

### ISSUE THREAD

**Issue by Develliot** [optimizely/react-sdk#126]
If I set up a client and provider, it adds 30KB (zipped) to to the main bundle that that is almost the same size as react-dom which feels a bit excessive for something that just needs to pump in client data to a useDecision hook. 

Is there anyway to reduce this overhead?

**Comment by Develliot** [comment]
it's almost as big as react dom, it's bigger than the next JS bundle. This wouldn't be a problem if I could lazy load this stuff when need but because it's not a component that's optional it's a wrapper than goes around every page as a provider that isn't an option. 


![Screenshot 2021-09-29 at 19 59 48](https://user-images.githubusercontent.com/5347198/135415621-b0139a8b-72d1-47db-9f73-1ef71b5c6279.png)

**Comment by Danny-Driscoll** [comment]
@Develliot Currently all of our SDKs including the client-side ones contain the logic to make user-level decisions based on environment-level configuration data, vs. being able to simply pass through existing decisions for an individual user, which is where the majority of the size currently comes from. We are looking at some longer term initiatives to provide thinner clients when those decisions are made elsewhere (either through a self-hosted [Agent](https://docs.developers.optimizely.com/full-stack/docs/optimizely-agent) or through other future hosted options), but do not yet have a timeline for those. For now I've created a record in our Product Feedback portal so we can track this as we work on those longer term initiatives. https://experimentation.ideas.aha.io/ideas/FSS-I-273
