### ISSUE TITLE
useDecision not evaluating correctly if user is updated with setUser

### ISSUE THREAD

**Issue by BrandonNoad** [optimizely/react-sdk#129]
After initialization, if I change the user associated with the ReactSDKClient using its `setUser` method, the decisions produced by `useDecision` for `flagKey`s that have been used previously do not evaluate correctly (the `userContext` for the decision is still the old user).

I think the error is due to the following check: `if (!areDecisionInputsEqual(prevDecisionInputs, currentDecisionInputs)) {`

The above check doesn't take into consideration the ReactSDKClient's current user.

If I use the overrides in the `useDecision` call e.g.

```
const result = useDecision(key, undefined, {
  overrideUserId: OptimizelyClient.user.id,
  overrideAttributes: OptimizelyClient.user.attributes,
});
```

then everything works as expected. But I shouldn't have to use the overrides.

Thanks.

**Comment by zashraf1985** [comment]
I have not tested this, but can you try it with sending `{autoUpdate: true}` as the second parameter to `useDecision`. the hook also listens separately to user updates but that's registered only when hook's `autoUpdate` option is `true`.

**Comment by zashraf1985** [comment]
if you set `{autoUpdate: false}` in the hook, it will only render once with whatever information it has and will never update. If you set it to `true`, that means, it will listen to user and datafile updates. It does not set `datafile` autoUpdate to true. It just means that if datafile is set to auto update, the hook will respond to those updates.
