### ISSUE TITLE
@Optimizely causing TS errors

### ISSUE THREAD

**Issue by pinkninjajess** [optimizely/react-sdk#142]
**My Setup/Config**
Running: "@optimizely/react-sdk": "^2.7.0",
"typescript": "^4.4.4"

**Tsconfig.ts**
has the following in **excludes**: "node_modules/**/*"
has "skipLibCheck": true set in **compilerOptions**

Hello, when running the command below @Optimizely has started to create 12 errors
`tsc --noEmit --project tsconfig.json`

Two sample errors:
```
node_modules/@optimizely/optimizely-sdk/lib/core/project_config/index.ts:167:19 - error TS2532: Object is possibly 'undefined'.

167     experiments = projectConfig.groupIdMap[Id].experiments;
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@optimizely/optimizely-sdk/lib/core/project_config/index.ts:222:11 - error TS2532: Object is possibly 'undefined'.

222           projectConfig.experimentFeatureMap[experimentId].push(feature.id);
```

Any idea why this might be happening all of a sudden? Thank you!

(Side note: seems similar to this older issue https://github.com/optimizely/javascript-sdk/issues/613)

**Comment by pinkninjajess** [comment]
Did some more testing, and I noticed in package-lock.json that the errors appear with the update to 4.9.0 from 4.8.0  
"@optimizely/optimizely-sdk": {
            "version": "4.8.0",

When I revert to 4.8.0, the errors disappear (same for a colleague working on a different project)

**Comment by zashraf1985** [comment]
Yes! It seems to be caused by the latest release of JavaScript SDK. I am looking in to it and will fix it soon.

**Comment by pinkninjajess** [comment]
Thank you!

**Comment by zashraf1985** [comment]
@pinkninjajess This is fixed. This was introduced by `@optimizely/optimizely-sdk` (Optimizely's Javascript SDK) which is used by our React SDK. We have fixed this in `@optimizely/optimizely-sdk` version `4.9.1`. Please do `yarn upgrade `@optimizely/react-sdk` or `npm update @optimizely/react-sdk` to pull in the latest version of the transitive dependency.

**Comment by pinkninjajess** [comment]
Thanks very much!!
