### ISSUE TITLE
OptimizelyProvider doesn't support user as Promise in componentDidUpdate

### ISSUE THREAD

**Issue by csims** [optimizely/react-sdk#144]
Hi there,

In the readme, it says that `OptimizelyProvider` can accept a `Promise` for a `user` object, and while this is supported in the [constructor](https://github.com/optimizely/react-sdk/blob/master/src/Provider.tsx#L49), it appears to not be supported in [`componentDidUpdate`](https://github.com/optimizely/react-sdk/blob/master/src/Provider.tsx#L73). My team ran into an issue with this on a Gatsby site, where a full page reload or navigation via anchor tag would populate the user info correctly, but navigating via client-side router doesn't.

Here's a small demo app that reproduces the issue, where the user passed to `OptimizelyProvider` is just a `Promise.resolve({ id: '123' })`: https://csims.github.io/optimizely-react-sdk-demo/

I'd be happy to take a stab at a fix this weekend if that's alright, but wanted to go ahead and get an issue open in the meantime.

**Comment by zashraf1985** [comment]
@csims Can you also share the source code repo for the demo you created

**Comment by csims** [comment]
Sure! The repo is here: https://github.com/csims/optimizely-react-sdk-demo, and I used `OptimizelyProvider` in https://github.com/csims/optimizely-react-sdk-demo/blob/master/src/pageWrapper.jsx .

**Comment by zashraf1985** [comment]
Thanks! I will take a deeper look at it later but i see you are using `useExperiment` with defauilt options. If you are passing in a promise for a user, you need to pass `autoUpdate: true` as an option to the hook. By default, the hooks just evaluate once. 
```
useExperiment('key', { autoUpdate: true })
```

https://docs.developers.optimizely.com/full-stack/docs/hooks-react

Can you give it a try and see if it works and let us know here?

**Comment by csims** [comment]
Good to know - thanks for pointing that out! I've added (and pushed/deployed) the change to add the `autoUpdate: true` option to `useExperiment`, but I still see the issue.

But I did just take another look at the readme and realized that I'm calling `createInstance` inside of the component in pageWrapper.tsx. It looks like moving it outside the component (so that it's not reinitialized upon SPA page transition) does appear to resolve the issue. That specific approach might not be possible in my team's use case since we get the datafile data from a prop passed to our wrapper component, but I might be able to accomplish the same thing with a `useRef`.

Given that, I leave it to you to determine whether this is something worth fixing or just a case of PEBKAC :)

**Comment by zashraf1985** [comment]
@csims The way we have currently designed our SDK is that we expect `OptimizelyProvider` to wrap the whole application. If you are facing problems in your implementation because of this, i would suggest you to go ahead and add a feature request. If we get enough votes, we can consider making that change in the SDK.

https://experimentation.ideas.aha.io/
