### ISSUE TITLE
Bundle size is too much

### ISSUE THREAD

**Issue by k4mr4n** [optimizely/react-sdk#146]
Hey guys!
Thanks for the awesome job.

I noticed that the bundle size for the useDecision hook is 32k gzipped which sounds huge comparing it to other libraries.
this is also the case for the provider.

I wonder if you have any plans to optimize this at some point?

<img width="673" alt="Screen Shot 2022-01-27 at 5 44 17 PM" src="https://user-images.githubusercontent.com/5468009/151455697-0a89134d-051a-47ee-b4ce-d3ebb9397e9e.png">

<img width="490" alt="Screen Shot 2022-01-27 at 5 45 09 PM" src="https://user-images.githubusercontent.com/5468009/151455791-35cdf2e5-41df-4ddc-8692-5100d402f835.png">

**Comment by Develliot** [comment]
See response here #126

**Comment by Danny-Driscoll** [comment]
Re-posting from #126 for visibility, thanks @Develliot. 

Currently all of our SDKs including the client-side ones contain the logic to make user-level decisions based on environment-level configuration data, vs. being able to simply pass through existing decisions for an individual user, which is where the majority of the size currently comes from. We are looking at some longer term initiatives to provide thinner clients when those decisions are made elsewhere (either through a self-hosted Agent or through other future hosted options), but do not yet have a timeline for those. For now I've created a record in our Product Feedback portal so we can track this as we work on those longer term initiatives. https://experimentation.ideas.aha.io/ideas/FSS-I-273
