### ISSUE TITLE
SDK-utils not updated

### ISSUE THREAD

**Issue by correttojs** [optimizely/react-sdk#15]
Getting the error TypeError: Cannot read property 'OPTIMIZELY_CONFIG_UPDATE' of undefined
After installing ` "@optimizely/js-sdk-utils": "^0.2.0",` it works, by default it install v0.1.0

**Comment by zashraf1985** [comment]
`@optimizely/js-sdk-utils` has been updated to `0.4.0`. Assuming this was fixed.
