### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by elliotwestlake** [optimizely/react-sdk#156]
We're currently upgrading to React 18 but getting this type error:
```typescript
error TS2322: Type '{ children: Element; optimizely: ReactSDKClient; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<OptimizelyProvider> & Readonly<OptimizelyProviderProps>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<OptimizelyProvider> & Readonly<OptimizelyProviderProps>'.

108     <OptimizelyProvider optimizely={optimizelyClientInstance}>
```

Would be nice for the repo to be updated to React 18, however, I see that's going to require a fair amount of work as you guys are using `enzyme` which doesn't look like it's going to support React 18 ever. So may need to migrate to RTL.

The simplest solution I can see now is to explicitly define a `children` prop to satisfy React 18.

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-typescript-definitions

Be great to hear your thoughts.

Thanks!

**Comment by opti-jnguyen** [comment]
Thanks for the input @wizardels - will discuss this issue with the team and post an update when we've decided on an approach to address it!
