### ISSUE TITLE
Bypass adblocks

### ISSUE THREAD

**Issue by k4mr4n** [optimizely/react-sdk#160]
Hello!

I'm using optimizely for our apps but some users cannot fetch the datafile because of their adblock extensions.
we cannot ask them to disable their adblock but we can implement a proxy in place. we can also fetch datafile on server side and pass it to the client but this might be blocking the requests.

First question: I want to know if there is any other way to bypass user's adblock?
Second: How can we pass our own URL to the optimizely provider for the datafileManager  to read the datafile from that URL instead, I believe we can use our proxy here

**Comment by zashraf1985** [comment]
A good way to bypass adblock is to fetch datafile from the url with same host name. Our SDK lets you define a `urlTemplate` to pull datafile from in the SDK Options. You can find more information about it in our docs [here](https://docs.developers.optimizely.com/experimentation/v4.0.0-full-stack/docs/initialize-sdk-react#customize-datafile-management-behavior). You can either proxy your url to optimizely CDN or host the datafile yourself and then keep updating it using the [Webhooks](https://docs.developers.optimizely.com/experimentation/v4.0.0-full-stack/docs/configure-webhooks). If you have further questions, please feel free to reach out.

**Comment by k4mr4n** [comment]
Thank you it worked beautifully 👍
