### ISSUE TITLE
OptimizelyProviderProps has no children props

### ISSUE THREAD

**Issue by NinaFan0824** [optimizely/react-sdk#168]
Hi there, when I use OptimizelyProvider in a typescript file, it shows the error below.
`Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<OptimizelyProvider> & Readonly<OptimizelyProviderProps>'.`

<img width="421" alt="Screenshot at Jun 09 23-26-44" src="https://user-images.githubusercontent.com/74746314/172836282-f5d15d8a-c63c-4220-ba62-8aabe968e2d4.png">

**Comment by NinaFan0824** [comment]
Hi there, I see a similar issue https://github.com/optimizely/react-sdk/issues/156 and I see the PR to add children prop. However, I couldn't find this prop in OptimizelyProviderProps interface. And I'm sure I download the latest version ` "@optimizely/react-sdk": "^2.8.1",`

<img width="787" alt="Screenshot at Jun 10 09-13-48" src="https://user-images.githubusercontent.com/74746314/172945595-d124c0d9-2515-4b5a-a4a5-df4611bad1ea.png">

**Comment by opti-jnguyen** [comment]
Hi @NinaFan0824 - thanks for raising this issue! 
Currently, v2.8.1 of the Optimizely React SDK does not support React 18.

We do have a fix in place that is unreleased and will be aiming to release a new version of the Optimizely React SDK with that fix for React 18 support sometime this week!
