### ISSUE TITLE
`onReady()` has significant performance issues

### ISSUE THREAD

**Issue by dominikjasek** [optimizely/react-sdk#192]
According to your [docs](https://docs.developers.optimizely.com/experimentation/v4.0.0-full-stack/docs/react-quickstart#:~:text=optimizelyClient.onReady().then(()%20%3D%3E%20%7B%0A%20%20%20%20setIsDone(true)%3B%0A%20%20%20%20isClientValid()%20%26%26%20setIsClientReady(true)%3B%0A%20%20%7D)%3B), we should delay rendering application with following code:

```ts
optimizelyClient.onReady().then(() => {
  setIsDone(true);
  isClientValid() && setIsClientReady(true);
});
```

This has significant performance issue in our application, it takes ~1s to initialize Optimizely this way. Do you have any recommendation to improve this? Maybe some caching strategy in localStorage or anything else?

Thanks

**Comment by mikechu-optimizely** [comment]
I've created an internal bug ticket (FSSDK-9623) to review/test contributing factors to resolving this Promise faster.

**Comment by mikechu-optimizely** [comment]
Hi @teichmaa and @dominikjasek We're in the process of releasing JS SDK v5.0.0 followed by React SDK v3.0.0 which removes the need to wait for a userContext during instantiation. This is a significant departure from previous versions.  

To accomplish this, we're establishing a visitor user ID (VUID) and using that as the identifier until the userContext (with a user ID) is established. 

For the sake of continuity, we still recommend awaiting the onReady to resolve but as of PR #229 I removed the userPromise in client.ts. 

The associated ticket above will help me revisit this issue and put benchmarks around instantiation and readiness.

Please keep the feedback coming. I appreciate the collab and the reports.

**Comment by teichmaa** [comment]
This is good news, thank you! Looking forward to the public release of JS SDK v5.0.0!

**Comment by mikechu-optimizely** [comment]
JS SDK just released.  I have to do 1-2 PRs to get React out the door.  I'll also see if I can run some manual e2e tests locally before the v3 release to spot problems.

**Comment by mikechu-optimizely** [comment]
We just released v3.0.0 of the SDK and would like feedback when you have a chance.

**Comment by mikechu-optimizely** [comment]
Update: I'm chasing down a performance report in the underlying JS SDK.  I want to make sure this is solved then come back to the onReady state.

**Comment by mikechu-optimizely** [comment]
JS SDK 5.0.1 is out. Today I'm pulling it into this SDK and begin load testing.

**Comment by mikechu-optimizely** [comment]
React 3.0.1 is out. I'm working to diagnose the `onReady()` delay when AAT is enabled.  

Does explicitly turning off AAT help as a workaround?

```js
const optimizelyClient = createInstance({
  sdkKey: "<sdk_key>",
  odpOptions: {
    disabled: true, // Not using Advanced Audience Targeting
  },
})
```

**Comment by mikechu-optimizely** [comment]
I'm testing this idea a bit more, but let's test putting the `onReadyPromise` into a `useEffect`

![image](https://github.com/optimizely/react-sdk/assets/104384559/2549b13c-cd75-4eb5-a599-1f66ceb3be4a)

```js 
//...
const optimizelyClient = createInstance({
  sdkKey: "<sdk-key>",
})
const onReadyPromise = optimizelyClient.onReady()

export default function App() {
  const [isDone, setIsDone] = useState(false)

  useEffect(() => {
    setIsDone(true)
  }, [onReadyPromise])
// ...
```

I'm continuing to dig further down the stack (likely into the JS SDK) to see how to improve the ready.

**Comment by mikechu-optimizely** [comment]
My test cases of putting `onReadyPromise` into the dependency array of `useEffect` does seem more performant, but that's just in my trivial test app. I'd love to hear from the real-world if you're available.  

I've jumped down into the JS SDK now and begun setting up clinicJS to thrash and measure `onReady` to profile for bottlenecks....

**Comment by mikechu-optimizely** [comment]
One of the things I'm noticing echos an Edge deployment of the JS SDK.  In this scenario, we typically advise that a local datafile be available as close as possible to `createInstance()`. For example, a local .json file that is updated via an external process or JSON stored in an Edge KV store. 

I'm seeing (in a node context) that the receiving and parsing the response from our CDN is actually the most latent portion of the flame chart 
![image](https://github.com/optimizely/react-sdk/assets/104384559/6ce9f999-b0a6-4f8e-8276-d65691f7e17e)
which is around 5.2% of the primary app excluding dependencies, node processes, etc
The next longest process is parsing the JSON to establish the experimental setup.

If I bring the same json local, reading it from disk, the longest delay occurs when parsing through the project JSON to establish the experiment setup 
![image](https://github.com/optimizely/react-sdk/assets/104384559/10dd39ee-181e-4180-88bd-a934dbb02c6c)
which is about 0.9% of the primary app excluding dependencies, node processes, etc.
The next longest process is user bucketing.

Actions to reduce `onReady` latency in performance situations:

1. Bring the datafile close to the execution, preferably in memory or local disk and update it outside the SDK
2. To continue using the SDK's polling for datafile updates, ensure QoS to the Optimizely CDNs.
3. Reduce the size of the json datafile by splitting experiments into different projects to reduce parsing time.
4. For React, try putting `onReadyPromise` into the dependency array of a `useEffect` illustrated yesterday ☝️ 

We could explore ways to optimize the datafile structure and JSON parsing, but these have deeper implications for this SDK and support Experimentation platform as a whole. I think we have a roadmap item for this.

Any additional evidence the community has is greatly appreciated as points of comparison. I'll hold the investigation open for a bit.
