### ISSUE TITLE
breaks all existing tests

### ISSUE THREAD

**Issue by joshpitzalis** [optimizely/react-sdk#22]
Adding optimizely rollouts to my react database breaks all my unit and integration tests. how do I mock out the optimizely wrapper in jest?

**Comment by VilliGunn** [comment]
Hi @joshpitzalis, have you figured out a solution?

**Comment by joshpitzalis** [comment]
I ended up writing wrapper components that pass the test boolean into the components. Then I just test the inner component without the wrapper. So yes and no, I found a solution but not one I ended up rewriting a lot of my tests in the process.

**Comment by joshpitzalis** [comment]
I'm using redux and react router with jest and react testing library.

I created a render function that takes rtl render and wraps it in all the providers I need, like so:

```
export const render = (
  ui,
  {
    route = '/',
    history = createMemoryHistory({ initialEntries: [route] }),
    initialState = {},
    store = configureStore(initialState),
    user = {
      id: 'xxx',
      attributes: {
        id: 'xxx',
      },
    },
    ...renderOptions
  } = {}
) => ({
  ...rtlRender(
    <Provider store={store}>
      <Router history={history}>
        <OptimizelyProvider optimizely={optimizely} user={user}>
          {ui}
        </OptimizelyProvider>
      </Router>
    </Provider>,
    renderOptions
  ),
  history,
  store,
});
```

Gets the job done for now, but I can't figure out how to mock out different configurations of flags being on and off. I opened a separate question for that, as my initial issue has kind of been solved with hoc and provider solution above. https://github.com/optimizely/react-sdk/issues/24
