### ISSUE TITLE
[BUG] Documentation: datafile initialization references wrong window object

### ISSUE THREAD

**Issue by jcshott** [optimizely/react-sdk#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK Version

current

### Current Behavior

The README references initializing the client with a datafile with `window.datafile` but the docs use the (correct) reference of `window.optimizelyDatafile` which is what the `tags.js` file loads the window object in.

https://docs.developers.optimizely.com/feature-experimentation/docs/initialize-sdk-react#instantiate-using-datafile

These should be consistent as users may not know/notice the difference.

### Expected Behavior

README should use `window.optimizelyDatafile`

### Steps To Reproduce

see README

**Comment by mikechu-optimizely** [comment]
Thanks @jcshott

**Comment by farhan-opti** [comment]
Hi @jcshott  The issue has been resolved in #224
