### ISSUE TITLE
[BUG] ReactSDKClient setUser() is not working

### ISSUE THREAD

**Issue by dtrenz** [optimizely/react-sdk#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK Version

`3.0.0`

### Current Behavior

When attempting to set the user ID on the Optimizely ReactSDK client using `setUser()` I see the following error when implementing a feature flag:
```
Unable to determine if feature "<feature key>" is enabled because User ID is not set
```

### Expected Behavior

Setting a user ID using `setUser()` should set the usr ID on the client.

### Steps To Reproduce

```tsx
import { createInstance, OptimizelyProvider } from "@optimizely/react-sdk";
 
const App = () => {
  const optimizelyClient = createInstance({
    sdkKey: "<key>",
  });

  optimizelyClient.setUser({ id: "12345" });

  return (
    <OptimizelyProvider optimizely={optimizelyClient}>
      <Children />
    </OptimizelyProvider>
  );
}
```

...then, in a child component:

```tsx
  const [isEnabled] = useFeature("<feature key>");
```

### React Framework

React 18.2.0 (Create React App + react-app-rewired)

### Browsers impacted

Reproducible in both Chrome and Safari. No other browsers were tested. The issue does not seem to be browser-specific.

### Logs

![Screenshot 2024-01-29 at 4 12 02 PM](https://github.com/optimizely/react-sdk/assets/639833/ab7c8b67-78d8-4232-85ea-333c5c36d62c)

### Workaround/Solution

I'm forced to abandon this approach and have to set the user ID via the `user` prop in `<OptimizelyProvider>`.

### Recent Change

No

**Comment by mikechu-optimizely** [comment]
Thanks for the report @dtrenz . Let me spin up a similar configuration as you've provided and try out.  I'll work on #235 at the same time.

**Comment by mikechu-optimizely** [comment]
I've added an internal ticket FSSDK-9985 into our next sprint.

**Comment by ricky-harrys** [comment]
I'm seeing this issue as well. It's being evaluated before the SDK is ready but it should be available in `<OptimizelyProvider />` at this point.

![Screenshot 2024-02-01 at 11 50 11 AM](https://github.com/optimizely/react-sdk/assets/107486935/1efe3c75-9f87-4ed0-b563-61aa9e574efe)

**Comment by danieleloscozzese** [comment]
I realise that the equivalent of a "+1" comment isn't necessarily helpful, but this bug has cost two separate colleagues of mine two different afternoons trying to debug configuration.
If the major has broken a principal interaction method, I would expect _some_ update after 6 weeks.

We have exactly the same issue as reported by @ricky-harrys.

If the ticket opened is internal, a status update would be helpful, or an `npm deprecate` to warn on the install.

**Comment by mikechu-optimizely** [comment]
Thanks for hanging in there as we align fixes for both the React and underlying JS SDKs. 

I've notified my manager that we need to look at both this and #235.  

Sorry about the low update counts here to keep you all apprised.  I will get updates and movement for you all shortly.

**Comment by mikechu-optimizely** [comment]
I pulled the App.tsx from the codesandbox provided and ran it against my proposed PR. 

![image](https://github.com/optimizely/react-sdk/assets/104384559/b2c297fb-364c-4430-a477-54440fa37237)

**Comment by mikechu-optimizely** [comment]
We've released v3.1.0 of the React SDK.  

When you have a moment, please let me know how this looks in a QA/Staging scenario.

**Comment by mikechu-optimizely** [comment]
I think this one should be solved.  

I just noticed some modifications that I'd suggest in the provided example:

```javascript

const optimizelyClient = createInstance({
  sdkKey: "<key>",
});

const App = () => {
  //optimizelyClient.setUser({ id: "12345" });

  return (
    <OptimizelyProvider optimizely={optimizelyClient} user={{ id: "12345" }}>
      <Children />
    </OptimizelyProvider>
  );
}
```
1. Let's move the user declaration into the `OptimizelyProvider` as a prop.  If you'd like to set a user later, let's put it in a `useEffect` hook.
2. Also consider moving the `optimizelyClient` outside the `App` component. Check out the [React Quickstart](https://docs.developers.optimizely.com/feature-experimentation/docs/react-quickstart#3-copy-the-sample-code) for an example.

**Comment by mikechu-optimizely** [comment]
Feel free to update here if needed.
