### ISSUE TITLE
[OptimizelyProvider UserAttributes Type Definition mismatch] The type definition for the user attributes does not match the documentation and is limiting types allowed

### ISSUE THREAD

**Issue by victor-optimizely** [optimizely/react-sdk#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK Version

3.1.0

### Current Behavior

The new package has defined the `UserAttributeValue` to be a limited set of types which contradicts the [documentation stating it supports any type](https://docs.developers.optimizely.com/feature-experimentation/docs/optimizelyprovider#props). What's happening now is that if you have a custom type being set as an attribute you will receive a typescript error because the type is not supported.

### Expected Behavior

The `user` prop in the `OptimizelyProvider` should allow any type definition as stated in the documentation instead of the currently defined type: 
```
export type UserAttributeValue = string | number | boolean | null;
```
⬇️ 
```
export type UserAttributeValue = any;
```
or simply:
```
export type UserAttributes = {
    [name: string]: UserAttributeValue;
};
```
⬇️ 
```
export type UserAttributes = {
    [name: string]: any;
};
```

### Steps To Reproduce

- setup a project with the lastest react sdk
- In the OptimizelyProvider's `user` prop, add a custom attribute that has a json value:
```
            <OptimizelyProvider
                optimizely={optimizelyInstance}
                user={{
                    id: profile?.id || null,
                    attributes: {
                        my_custom_attribute: { name: "something", type: "something" },
                    }
                }}
            >
                {children}
            </OptimizelyProvider>
```
Note the TS error:
![image](https://github.com/optimizely/react-sdk/assets/106699333/0a741a91-0a67-46c0-82b1-15243e74a55a)

### React Framework

create-react-app

### Severity

Blocking development

### Workaround/Solution

Solution listed above. Workaround might be to ts-ignore and ensure the attribute is being used.

**Comment by junaed-optimizely** [comment]
@victor-optimizely, is this ticket still valid?
