### ISSUE TITLE
[BUG] Random error with initialization client

### ISSUE THREAD

**Issue by kimyu92** [optimizely/react-sdk#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK Version

react-sdk v3.1.0

### Current Behavior

We currently have logs indicating random requests getting the following error

message:Request error stack:Error: Request error at responsePromise.n.onreadystatechange

![image](https://github.com/optimizely/react-sdk/assets/2663509/dc4429d5-01a9-4d5f-98a5-0675a811490e)

### Expected Behavior

No error

### Steps To Reproduce

```javascript
// or this is written inside useEffect
const client = createInstance({
    sdkKey: 'SDK_KEY',
    datafileOptions: {
      autoUpdate: true,
      updateInterval: 300000,
    },
    eventBatchSize: 10,
    eventFlushInterval: 1000,
    errorHandler: {
      handleError: (e: Error) => {
        console.log(e.message, e.stack);
      },
    },
    odpOptions: {
      disabled: true,
    },
});

const OptimizelyFlagProvider = () => {
  // some useState
  
  useEffect(() => {
    const isClientValid = () => {
      return client?.getOptimizelyConfig() !== null;
    };

    client?.onReady().then((ocInstance: OnReadyResult) => {
      if (isClientValid()) {
          // set valid state
      }
      else {
          // set error state
      }  
    }(
  }, []);
  
  return (
    <OptimizelyProvider optimizely={client} timeout={500} user={{ id: 'userId' }}>
       // error and successful body {....}
    </OptimizelyProvider>
   );
}
```

### React Framework

18.2.0

### Browsers impacted

Chrome latest version

### Severity

Affecting users

**Comment by junaed-optimizely** [comment]
@kimyu92 , due to inactivity, I am closing this issue. If you have more details or the issue occurs again, please feel free to reopen it. 

Thanks!
