### ISSUE TITLE
Does react-sdk use any DOM APIs? Is react-native supported?

### ISSUE THREAD

**Issue by alexmbp** [optimizely/react-sdk#41]
Hello Optimizely!

I'm investigating options for doing experiments in my react-native app. Does this SDK use any DOM/browser APIs that might block me from using the sdk with react-native?

I verified that it works with react-native, but should I expect it will continue working that way?

**Comment by mjc1283** [comment]
Hey @alexmbp,

You can expect React SDK to continue working in React Native. Furthermore, our roadmap has  several enhancements to make the SDK more useful in React Native apps. We are replicating some of the mobile-specific functionality that exists our [Swift SDK](https://github.com/optimizely/swift-sdk) and [Android SDK](https://github.com/optimizely/android-sdk). We are now hard at work on the first of these roadmap items: persistent datafile caching. If you have any feedback on using the SDK, please let us know. Thanks!

**Comment by alexmbp** [comment]
Thanks, @mjc1283 ! Everything is good so far. I like hooks api that was recently added!
What can be a useful thing -> debugger support. Some libraries were able to achieve it using redux devtools (you could check it here https://github.com/react-navigation/react-navigation/blob/179b6312fedc02dff23346e6b4849d6f06eb28af/packages/core/src/useDevTools.tsx)

So, redux is not used to store values, but used just to fire events. For optimizely it could be like:
'feature state updated' or whatever might be useful for logging / debugging.

**Comment by Tamara-Barum** [comment]
Internal Ticket: [FSSDK-8656]

**Comment by Tamara-Barum** [comment]
Review and closing as non-issues with updates provided.
