### ISSUE TITLE
Export OptimizelyReactSDKClient as interface or type

### ISSUE THREAD

**Issue by kylemh** [optimizely/react-sdk#49]
The return value of `createInstance` (`OptimizelyReactSDKClient`) should be exported as a type, lest we need to use `ReturnType<typeof createInstance>`

**Comment by avifoxi** [comment]
@kylemh it is -> 
```ts
import { ReactSDKClient } from '@optimizely/react-sdk'
```

**Comment by kylemh** [comment]
No, I mean `OptimizelyReactSDKClient` which extends off of `ReactSDKClient` and is the explicit return type for `createInstance`: https://github.com/optimizely/react-sdk/blob/6e6f1b43c00653e89da5a4dc8bc0fc7354bb8386/src/client.ts#L670

**Comment by matthewbordas** [comment]
I agree. I ran into this issue this week. It would be really helpful to have this updated!

**Comment by kylemh** [comment]
I am not at the company that had this issue, so I won't be able to confirm for you, but I bet it works great!
