### ISSUE TITLE
Question about user id

### ISSUE THREAD

**Issue by darewreck54** [optimizely/react-sdk#52]
I'm still learning how to use optimizely, so please bear with me.  How are you suppose to configure an audience based on the user {id} that is passed in. I want to configure a feature flag with a specific audience that is based of a set of user id.  However, when i try to configure an audience with the attribute (id) it doesn't work.  The only way i can do it is if i add the id as an attribute to the attribute object.

```
  <OptimizelyProvider
              optimizely={this.optimizely}
              user={{
                id: userEmail,
                attributes: { id: userEmail } 
              }}
```

Thanks,
Derek

**Comment by hpurra** [comment]
@darewreck54 https://docs.developers.optimizely.com/full-stack/docs/use-whitelisting

**Comment by Tamara-Barum** [comment]
Closed per documentation linked. no further questions asked.
