### ISSUE TITLE
Feature Request: unable to determine if a feature is turned off

### ISSUE THREAD

**Issue by seansean11** [optimizely/react-sdk#57]
Currently, when using both the `useFeature` hook and the `OptimizelyFeature` component, the only feature specific data you are returned are whether your experiment `isEnabled` and the `variables` associated with that feature.  This works well when you want to toggle between two options while your feature is toggled `on`, but does not provide the client with any information about whether your feature is on or off.  If the client receives `isEnabled` of `false`, it could mean that your feature is turned off, or it could mean that the user did not fall in the segment or group that should have the feature enabled.  I'd like to propose that the hook and component return an additional value of whether the feature is toggled `on` or `off`.  In our case, we would like to fallback to different functionality when the feature is off.

I'd be happy to add a PR, if this is something that your devs are willing to add.

**Comment by Danny-Driscoll** [comment]
We have introduced a new additional method for retrieving decisions, with a corresponding hook, useDecision. This hook now returns an object with additional decisionContext and metadata. There is an option to include a full record of decision reasons, similarly to the info logs that we produce for decisions. https://docs.developers.optimizely.com/full-stack/v4.0/docs/optimizelydecision-react
