### ISSUE TITLE
react hooks

### ISSUE THREAD

**Issue by husseinraoouf** [optimizely/react-sdk#6]
will this sdk ever support react hooks?

**Comment by alexparish** [comment]
Migrating to React Hooks would have the added benefit of reducing bundle sizes as functional components could be utilised instead of classes that require transpilation for older browsers.

**Comment by zcramos** [comment]
:+1:

Migrating to hooks would be really nice, but just exporting the `createContext({...})` from `src/Context.js` (rather than only exporting the consumer and provider) would allow consumers to take advantage of the `useContext` hook for a more pleasant API.

**Comment by jamesopti** [comment]
Hooks for `useExperiment` and `useFeature` have been merged and released with #40 ! The entire context object is now exported as well, enabling consumers to write their own hooks.
