### ISSUE TITLE
Integrating with React Redux

### ISSUE THREAD

**Issue by NickIannelli** [optimizely/react-sdk#63]
My apologies if this has been addressed before - I have searched through the docs, issues & closed issues to no avail.

Do you have guidelines for integrating the optimizely SDK into redux? For our project we have done some hacky work to listen to the `OptimizelyFeature` status and synchronise the experiment status to the store when it gets mounted, however this feels more like a workaround than a feature.

Wondering if you have any best-practice guidelines for integrating with Redux? Many thanks.

**Comment by jamesovens** [comment]
I'm looking for exactly the same thing, and the hacky workaround you described is exactly what I am going to try now.
We previously were using Launch Darkly and the LD client allows you to listen for flag changes which means you can use that instead and I was hoping for something similar to that in optimizely but nothing I can see.

**Comment by jamesovens** [comment]
Also @NickIannelli did your solution include having some way to update the redux store once a feature flag changes value after the initial load of the feature flag value?
I had assumed that Optimizely would push an event when a flag was updated, the same as how Launch Darkly worked (which I think kept a socket open to allow this), but it seems they do not which is unfortunate for us as we have been using Redux and Launch Darkly to be able to make large changes across our app as soon as somebody changes a flag's value in Launch Darkly.

**Comment by jamesovens** [comment]
Okay it looks like you have to set 
```
datafileOptions: {
	autoUpdate: true,
	updateInterval: 1000
}
```
when creating the optimizely client, and then you have to set
`autoUpdate={true}`
on the OptimizelyFeature component

**Comment by jamesovens** [comment]
I added this in the issue I opened at https://github.com/optimizely/react-sdk/issues/73 but I'll add it here too as this is how I am now getting all the feature flag values (including updates) to be pushed into Redux using the optimizely client only and it seems pretty clean:

I found this in the docs: https://docs.developers.optimizely.com/full-stack/docs/optimizelyconfig-update-notification-listener
In order to get a callback for whenever the datafile changes (when the feature flag value changes) you can do the following:
```
  const optimizelyClient = createInstance({
    sdkKey: "<YOUR_SDK_KEY>",
    datafileOptions: {
      autoUpdate: true,
      updateInterval: <ANY_INTERVAL_YOU_WANT>
    }
  });

  optimizelyClient.notificationCenter.addNotificationListener(
    enums.NOTIFICATION_TYPES.OPTIMIZELY_CONFIG_UPDATE,
    notificationData => {
      console.log("Datafile is updated : ", notificationData);
	  // At this point you want to now use the optimizelyClient to query for the latest value of
	  // all your feature flags and then do what you want with them (including push them into redux)
    }
  );
```

**Comment by Danny-Driscoll** [comment]
Thanks for sharing your solution!
