### ISSUE TITLE
Could not import @optimizely/react-sdk

### ISSUE THREAD

**Issue by haoran-eb** [optimizely/react-sdk#67]
After I used
`yarn add @optimizely/react-sdk`
And it was beed added in package.json
![image](https://user-images.githubusercontent.com/54050068/91680827-1db50d00-eb7f-11ea-8f6e-c32cb95c7b2c.png)

But when I import it in React like this
![image](https://user-images.githubusercontent.com/54050068/91680851-345b6400-eb7f-11ea-8b6a-3a3b5b858ad0.png)
It will report warning in console.
![image](https://user-images.githubusercontent.com/54050068/91680885-50f79c00-eb7f-11ea-8ba0-15b53509e05f.png)

And I debug in the frontend, I will stop at the point of import
![image](https://user-images.githubusercontent.com/54050068/91692276-b22d6880-eb9b-11ea-8c1b-c00cb96a5ce7.png)

Did I do something wrong or need some other settings?
Thanks for helping!

**Comment by patrickgordon** [comment]
try this

```
import { createInstance, OptimizelyProvider } from "@optimizely/react-sdk/dist/react-sdk";
```

**Comment by haoran-eb** [comment]
@patrickgordon Thanks, It’s not the problem you said, but I found an error in webpack. I have a @react-native-community/async-storage package that was not added, resulting in
`node_modules/@optimizely/react-sdk/node_modules/@optimizely/js-sdk-utils/lib/reactNativeAsyncStorageCache.js` report error
I added it and it success.
![image](https://user-images.githubusercontent.com/54050068/91922745-42d18900-ed01-11ea-8d99-9a270c475cad.png)
Thanks!
