### ISSUE TITLE
Ability to turn off INFO logging?

### ISSUE THREAD

**Issue by jamesmosier** [optimizely/react-sdk#68]
Hi 👋  Is there a way to disable all the INFO logging messages that are output to the browser's console?

```
[OPTIMIZELY] - INFO  2020-09-09T18:06:27.879Z DatafileManager: Updating datafile from response
[OPTIMIZELY] - INFO  2020-09-09T18:06:27.880Z PROJECT_CONFIG: Skipping JSON schema validation.
[OPTIMIZELY] - INFO  2020-09-09T18:06:27.881Z OPTIMIZELY: Updated Optimizely config to revision 103 (project id 1234)
```

If not, would you all be open to a PR for this?

**Comment by arisrais** [comment]
you can use `logLevel` option : 

`const optimizlyConnector = createInstance({
  sdkKey: process.env.REACT_APP_OPTIMIZLY_KEY,
  datafileOptions: {
    updateInterval: 120 * 1000, // milliseconds
    autoUpdate: true
  },
  logLevel: process.env.NODE_ENV === 'development' ? LogLevel.INFO : LogLevel.ERROR
});`

**Comment by jamesmosier** [comment]
Thanks @arisrais 🚀 

I didn't find a `LogLevel` export from `@optimizely/react-sdk` but I did find `enums.LOG_LEVEL`:

```js
import {
  createInstance,
  enums,
} from '@optimizely/react-sdk';

const optimizely = createInstance({
  sdkKey: process.env.OPTIMIZELY_SDK_KEY,
  logLevel: enums.LOG_LEVEL.ERROR,
});
```
