### ISSUE TITLE
CONFIG_VALIDATOR: No datafile specified. Cannot start optimizely.

### ISSUE THREAD

**Issue by devonjs** [optimizely/react-sdk#72]
Upon upgrading to 2.3.X, we get the the following error `CONFIG_VALIDATOR: No datafile specified. Cannot start optimizely.`, however Optimizely seems to load everything after the datafile is updated from the http response for the datafile.

![Screen Shot 2020-10-06 at 9 06 05 AM](https://user-images.githubusercontent.com/10638459/95227847-76497c80-07b3-11eb-8ef0-42960573fe19.png)

Is there a way to turn off the initial error message?  So far I've tried increasing the `timeout` in the `OptimizelyProvider` to no avail.

**Comment by arisrais** [comment]
Same problem !!

**Comment by stefanstaynimble** [comment]
Same issue also.

**Comment by devonjs** [comment]
Closing, looks fixed to me in `2.3.2`
