### ISSUE TITLE
ReactSDKClient onDataFileUpdate function

### ISSUE THREAD

**Issue by jamesovens** [optimizely/react-sdk#73]
Hi,

I see in the ReactSDKClient there are functions like onUserUpdate that provide a way to get a callback when the user update happens or onReady for when the client initialises. I am wondering if there is a way to add an onDataFileUpdate function that would provide the same functionality but for when an update to the datafile occurs.

For example if I initialise the Optimizely client with:
```
datafileOptions: {
  autoUpdate: true,
  updateInterval: 1000
}
```
Then it will poll for datafile updates and if a feature flag has its value changed then it will redownload the new datafile. At this point if any of the `<OptimizelyFeature>` components have autoUpdate set to true then they will get updated when this new datafile with new flag value is downloaded.

If an onDataFileUpdate function with a callback was provided then we would be able to listen for these same changes using the ReactSDKClient, which allows us to do more with the feature flags, such as push the changes into Redux.

**Comment by jamesovens** [comment]
Okay so I managed to find a way to do this by using the Notification Center instead. I found this in the docs: https://docs.developers.optimizely.com/full-stack/docs/optimizelyconfig-update-notification-listener
In order to get a callback for whenever the datafile changes (when the feature flag value changes) you can do the following:
```
  const optimizelyClient = createInstance({
    sdkKey: "<YOUR_SDK_KEY>",
    datafileOptions: {
      autoUpdate: true,
      updateInterval: <ANY_INTERVAL_YOU_WANT>
    }
  });

  optimizelyClient.notificationCenter.addNotificationListener(
    enums.NOTIFICATION_TYPES.OPTIMIZELY_CONFIG_UPDATE,
    notificationData => {
      console.log("Datafile is updated : ", notificationData);
	  // At this point you want to now use the optimizelyClient to query for the latest value of
	  // all your feature flags and then do what you want with them (including push them into redux)
    }
  );
```

**Comment by Danny-Driscoll** [comment]
Thanks for updating James, one note would be that this listener currently fires when we have retrieved a new datafile from our CDN due to polling, not specifically when there is a changed feature flag entity within the datafile. We will look to introduce more incremental and intelligent updates over time but for now this is the correct listener to hook into.
