### ISSUE TITLE
Is there a way to use event tracking without the HoC

### ISSUE THREAD

**Issue by grug** [optimizely/react-sdk#78]
Hi there!

The docs suggest to track metrics for an experiment that you need to use the withOptimizely HoC. Is there a hook available to do this, instead?

Thanks!

**Comment by tbgse** [comment]
wondering about exactly the same

**Comment by tbgse** [comment]
@grug after looking through the source a bit more we came up with the following to build our own tracking hook:

```
import {  OptimizelyContext } from '@optimizely/react-sdk';
export function useOptimizelyTrack() {
  const { optimizely } = useContext(OptimizelyContext);
  return (val) => optimizely.track(val);
}
```

I hope this gives you something to get started with.

**Comment by grug** [comment]
@tbgse very cool :) 

I wonder if we could open a PR into this repo to add this. Trying to think of any repercussions of having this hook written like this.

**Comment by tbgse** [comment]
It's probably a good idea to create a PR but i don't have the time at the moment to fully write out the hook (it'd also need  to support overrides, passed tags `return (val, overrides, tags) => optimizely.track(val, overrides, tags);` be typed correctly and require some tests to be added to the `hooks.spec.tsx`. 

Hoping that someone from optimizely might find this issue and take the initiative

**Comment by erni-cap** [comment]
Hi @tbgse , I'm trying out the hook example you posted above, and I can see in the network tab that an event is being sent, but there's no evidence of the event-key in the call. Because of that the experiment metrics aren't changing.

Basically like this:

``` typescript
const trackEvent = useOptimizelyTrack()

function handleEvent() {
    trackEvent('start-button-click')
}

 return (
    <div onClick={handleEvent}></div>
)
```

This is a component inside of App which is wrapped in the OptimizelyProvider

Am I missing something?

**Comment by erni-cap** [comment]
To follow up with the previous post, I've updated the hook to include the userId, but Optimizely still isn't receiving the event clicks.

```
export function useOptimizelyTrack() {
    const { optimizely } = useContext(OptimizelyContext)
    return (val) => optimizely.track(val, optimizely.user.id)
}```

**Comment by tbgse** [comment]
Hey @erni-cap i just had a quick look at our codebase and we actually pass a third argument (data) which defaults to an empty object e.g. `optimizely.track(val, optimizely.user.id, {})`

I'm not sure if that might already fix your problem, otherwise i can try to have another look.

**Comment by erni-cap** [comment]
I gave that whirl, but it's still not showing up in the experiment. Is there some lag for click events to show up?

**Comment by erni-cap** [comment]
I learned that the userId wasn't ready in time for the track hook to have access to the userId. @tbgse , your original hook solution worked with just sending `val`
