### ISSUE TITLE
build to umd (and system?) format? 

### ISSUE THREAD

**Issue by frehner** [optimizely/react-sdk#79]
Wondering if you would be open to building to umd (and system) formats?

looking at https://github.com/optimizely/react-sdk/blob/master/scripts/build.js it seems like we could just add another line like the following

```js
exec(`./node_modules/.bin/rollup -c scripts/config.js -f umd -o dist/${packageName}.umd.js`);

// and maybe system format?
exec(`./node_modules/.bin/rollup -c scripts/config.js -f system -o dist/${packageName}.system.js`);
```

shouldn't have any side effects, since the entry points will remain the same and these are just new files being built.

if you're open to it, I can make the PR as well

**Comment by mjc1283** [comment]
Hi @frehner ,
We are definitely open to it, but I have one question. We have a UMD build in our core SDK module (@optimizely/optimizely-sdk), but it pulls all dependencies into the bundle. The goal is for it to be usable in a browser by loading it standalone via a script tag. If I'm not mistaken, #80 is not pulling all the dependencies into the bundle. Would you need that for your use case, or is it fine as-is?

**Comment by frehner** [comment]
my setup is one where we're using SystemJS to provide certain modules in the browser at runtime (somewhat similar to RequireJS if that helps), so it would probably work.

however, even on master with no changes I couldn't get the build script to work in order to see what the output bundle would actually look like (e.g. looking at the `define` call for umd or looking at the `System.register` call for systemjs) so I can't be certain.

perhaps if you could help me figure out why that's failing then I could take a look and confirm?

**Comment by frehner** [comment]
ah just merged in latest from master and that seems to fix it now. one moment.

**Comment by frehner** [comment]
Here's the umd build:

```js
define(['exports', 'react', '@optimizely/js-sdk-logging', 'hoist-non-react-statics', '@optimizely/optimizely-sdk'],
```

and here's the system build: 

```js
System.register(['react', '@optimizely/js-sdk-logging', 'hoist-non-react-statics', '@optimizely/optimizely-sdk'],
```

I think in an ideal world we can leave React in those dep arrays, but bundle the rest directly in so the consumer of these bundles doesn't have to.

For reference, that's how React Router handles its UMD build:

https://cdn.jsdelivr.net/npm/react-router-dom@5.2.0/umd/react-router-dom.js

What are your thoughts?

**Comment by mjc1283** [comment]
Yea, that makes sense 👍 . If you want to include that change in #80 or another PR, please feel free.

Unfortunately the build script is a little weird. IMO, it should be replaced with a more standard Rollup config file. If it ends up getting in your way, we can tackle that problem sooner, or later if not.

**Comment by frehner** [comment]
@mjc1283 I've updated the PR. however, I had to also update rollup and its plugins in order for the builds to build correctly (see the note in the PR). just wanted to give you a heads up

**Comment by frehner** [comment]
just wanted to chime in that I added the system build to my infrastructure and it's working great so far. 

so thank you for your help in resolving this quickly. 💯
