### ISSUE TITLE
Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'

### ISSUE THREAD

**Issue by axeffwettercom** [optimizely/react-sdk#84]
Happens while building (babel always turns on --isolatedModules flag)

> Failed to compile.
> 
> ./node_modules/@optimizely/optimizely-sdk/lib/core/event_processor/index.ts:25:10
> Type error: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
> 
>  23 | }
>  24 |
> \> 25 | export { EventProcessor, LocalStoragePendingEventsDispatcher } from '@optimizely/js-sdk-event-processor';
> |......................^
>   26 |
>   27 | export default { createEventProcessor, LocalStoragePendingEventsDispatcher };
>   28 |

**Comment by fmacherey** [comment]
We figured out, that this error is from the `optimizely-sdk@4.4.0`. It has already been fixed a few hours ago here https://github.com/optimizely/javascript-sdk/commit/c5301c55be0e1ba2e4ccf07adf245ff197c3953e#diff-5cc4327a727813f25d0da674bce60ae0c71cf2185af0d9ea4e70d0532072d275 and needs to be published with version 4.4.1. Than the react-sdk should also update it's deps. 

We tried to downgrade, but in the react-sdk is a semver with `^4.3.4`, so yarn will always install `4.4.0`.

Do you have a suggestion, when to release the bugfix versions?
Thanks for your help.

**Comment by mjc1283** [comment]
@fmacherey We are planning to release `@optimizely/optimizely-sdk` v4.4.1 today containing the fix you referenced. Thanks for your patience.

**Comment by grantglidewell** [comment]
It appears Optimizely ships a .ts file and expects anyone using TypeScript to compile it, however it doesnt pass strict TS configs. Is there a plan to ship compiled code? Even with this recent fix we are still having compile issues when trying to upgrade.

**Comment by fmacherey** [comment]
@mjc1283 Do you have a plan, when you upgrade the react-sdk version, to use the fixed optimizely-sdk version, you released last week? Yarn will still install optimizely-sdk@4.4.0 as a dependency.

Thanks for your help :)

**Comment by mjc1283** [comment]
@grantglidewell That sounds similar to what others have reported on https://github.com/optimizely/javascript-sdk/issues/613. For the `@optimizely/optimizely-sdk` package, our intent was not to make anyone compile our TS source code. We provide plain JS files in the dist/ directory, and refer to those files in package.json's "main", "browser", "module", etc. fields. Is there an issue using those plain JS files in your project/build setup?

**Comment by jaymendez** [comment]
Any updates on this or any temporary fix?

**Comment by axeffwettercom** [comment]
@jaymendez Looks like it should be fixed with #88

**Comment by yavorona** [comment]
@axeffwettercom @fayyazarshad @grantglidewell @fmacherey @jaymendez please upgrade to [react-sdk v2.4.1](https://github.com/optimizely/react-sdk/releases/tag/2.4.1) where we fixed this issue. Thanks!
