### ISSUE TITLE
Allow `default` to be set on an OptimizelyVariation that has `variation` also set

### ISSUE THREAD

**Issue by grug** [optimizely/react-sdk#86]
This would be a nice quality of life improvement to have as we often have experiment code that looks like this:

```tsx
<OptimizelyExperiment experiment="some_test">
  <OptimizelyVariation variation="original">
    <OriginalComponent />
  </OptimizelyVariation>
  <OptimizelyVariation variation="some_variant">
    <VariantComponent />
  </OptimizelyVariation>
  <OptimizelyVariation default>
    <OriginalComponent />
  </OptimizelyVariation>
</OptimizelyExperiment>
```

It would be nice to be able to express the above as:

```tsx
<OptimizelyExperiment experiment="some_test">
  <OptimizelyVariation default variation="original">
    <OriginalComponent />
  </OptimizelyVariation>
  <OptimizelyVariation variation="some_variant">
    <VariantComponent />
  </OptimizelyVariation>
</OptimizelyExperiment>
```

As it is more concise and just as readable.

Is there a chance of seeing this improvement land in the SDK?

-Dave

**Comment by Tamara-Barum** [comment]
Internal ticket created: [FSSDK-8653]

**Comment by alexparish** [comment]
I'm very keen on this change as my company has has production incidents due to misunderstandings around how this works. It was assumed that adding a `default` attribute to an `<OptimizelyVariation>` component with a `variation` would suffice.

If the internal ticket hasn't been progressed, would you welcome a pull request?

**Comment by mikechu-optimizely** [comment]
I'm working on this Issue and #225 in this sprint. 

Always welcome pull requests.  This helps all stakeholders (including internal) understand the requirement / POV as well as shorten up the implementation.

**Comment by mikechu-optimizely** [comment]
I have a dependent branch ready with this bug fix and test coverage.

**Comment by junaed-optimizely** [comment]
Seems like it has been released a while ago.. Closing..!
